### ISSUE TITLE
Needs adding to packagist

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_extra_layouts#3]
Currently can't install unless adding to composer.json as a repo.

**Comment by markconroy** [comment]
@andybroomfield Any thoughts on https://github.com/localgovdrupal/localgov_extra_layouts/issues/1

Should we add all these new layouts to our default paragraphs module, or should we keep this as an independent module for extra layouts that some councils might want and others might not?

When we decide that, we can know if we need to add this to packagist or not.

(Please chip in on https://github.com/localgovdrupal/localgov_extra_layouts/issues/1 rather than here)

**Comment by markconroy** [comment]
Done - https://packagist.org/packages/localgovdrupal/localgov_extra_layouts

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
